name: Docker Login and Push
on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use access token instead of password

      - name: Build and Push Docker Image
        run: |
          docker build -t my-image:latest .
          docker tag my-image:latest my-dockerhub-username/my-image:latest
          docker push my-dockerhub-username/my-image:latest
